version: "3.0"
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - "./docker/db/pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "theeye"

  localstack-s3:
    image: localstack/localstack:0.11.4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1

  redis:
    image: redis:5.0
    ports:
      - "6379:6379"
