name: Run tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    services:
      db:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: "theeye"
          POSTGRES_DB: "theeye"

    steps:
      - name: Prepare container
        run: apt-get update && apt-get install -y binutils libproj-dev gdal-bin

      - uses: actions/checkout@v2

      - name: Istall requirements
        run: pip install -r requirements.txt

      - name: Install test requirements
        run: pip install coverage mock freezegun codecov

      - name: Copy env.test to .env
        run: mv env.test .env

      - name: Export environment variables
        run: while read -r line; do echo "$line" >> $GITHUB_ENV; done < <(grep -E -v "(^#|^\s|^$)" .env)
        shell: bash

      - name: Run tests
        run: coverage run --source='.' manage.py test
        env:
          AWS_ACCESS_KEY_ID: "foo"
          AWS_SECRET_ACCESS_KEY: "bar"
          AWS_DEFAULT_REGION: "us-east-1"
          DATABASE_URL: "postgres://postgres:theeye@localhost:5432/theeye"
          ENVIRONMENT: "test"
